FROM python:3.9-buster

RUN mkdir -p /hackernewsdocker

WORKDIR /hackernewsdocker

COPY ./requirements.txt /hackernewsdocker/requirements.txt

RUN pip install -r requirements.txt

COPY . /hackernewsdocker