# Generated by Django 4.1.1 on 2022-09-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
