# Generated by Django 4.1.1 on 2022-09-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsitem_kids_alter_newsitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
