# Generated by Django 4.1.1 on 2022-09-21 10:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_id', models.IntegerField(default=0)),
                ('parent_id', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('news', 'News'), ('story', 'Story'), ('comment', 'Comment')], max_length=10)),
                ('deep_comments', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, default=list, null=True, size=None)),
                ('timestamp', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsitem')),
            ],
        ),
    ]
